apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: xn4pgum2y-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xn4pgum2y-nodejs 
  name: xn4pgum2y-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: xn4pgum2y-nodejs 
